---
# tasks file for artifactoryrole
- name: artifactory | Install dependencies
  yum: pkg={{ item }} state=installed
  with_items:
    - unzip
    - net-tools
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
  tags: artifactory

- name: install zip file 
  get_url: url={{ artifactory_url }}  dest=/opt/{{ artifactory_tar_zip }}

- name: Extract archive
  unarchive:
   src: /opt/{{ artifactory_tar_zip }}
   dest: /opt/
   remote_src: yes 
   extra_opts: [--strip-components=1]

- name: installing artifactory
  shell: cd {{ artifactory_dir }}/bin

- name: start artifactory
  shell: name=artifactory state=started
  
- name: Adding the path in the Profile files
  lineinfile: dest=/home/ec2-user/.bash_profile line='export ARTIFACTORY_HOME={{ artifactory_dir }}' state=present

- name: Run command if /path/to/install.sh does exist
  command: /opt/app/bin/installService.sh
  tags: installservice

- name: checkconfig on
  command: systemctl is-enabled artifactory.service
  tags: check

- name: Start service artifactory, if not started
  service:
    name: artifactory.service
    state: started
    tags: service

  